/* eslint-disable import/prefer-default-export */
// let buttons = document.querySelectorAll(".button");
// let buttonsObj = {
//   Backquote: buttons[0],
//   Digit1: buttons[1],
//   Digit2: buttons[2],
//   Digit3: buttons[3],
//   Digit4: buttons[4],
//   Digit5: buttons[5],
//   Digit6: buttons[6],
//   Digit7: buttons[7],
//   Digit8: buttons[8],
//   Digit9: buttons[9],
//   Digit0: buttons[10],
//   Minus: buttons[11],
//   Equal: buttons[12],
//   Backspace: buttons[13],
//   Tab: buttons[14],
//   KeyQ: buttons[15],
//   KeyW: buttons[16],
//   KeyE: buttons[17],
//   KeyR: buttons[18],
//   KeyT: buttons[19],
//   KeyY: buttons[20],
//   KeyU: buttons[21],
//   KeyI: buttons[22],
//   KeyO: buttons[23],
//   KeyP: buttons[24],
//   BracketLeft: buttons[25],
//   BracketRight: buttons[26],
//   Backslash: buttons[27],
//   Delete: buttons[28],
//   CapsLock: buttons[29],
//   KeyA: buttons[30],
//   KeyS: buttons[31],
//   KeyD: buttons[32],
//   KeyF: buttons[33],
//   KeyG: buttons[34],
//   KeyH: buttons[35],
//   KeyJ: buttons[36],
//   KeyK: buttons[37],
//   KeyL: buttons[38],
//   Semicolon: buttons[39],
//   Quote: buttons[40],
//   Enter: buttons[41],
//   ShiftLeft: buttons[42],
//   KeyZ: buttons[43],
//   KeyX: buttons[44],
//   KeyC: buttons[45],
//   KeyV: buttons[46],
//   KeyB: buttons[47],
//   KeyN: buttons[48],
//   KeyM: buttons[49],
//   Comma: buttons[50],
//   Period: buttons[51],
//   Slash: buttons[52],
//   ArrowUp: buttons[53],
//   ShiftRight: buttons[54],
//   ControlLeft: buttons[55],
//   Win: buttons[56],
//   AltLeft: buttons[57],
//   Space: buttons[58],
//   AltRight: buttons[59],
//   ArrowLeft: buttons[60],
//   ArrowDown: buttons[61],
//   ArrowRight: buttons[62],
//   ControlRight: buttons[63],
// };

class Highlight {
  addHighlight() {
    const buttons = document.querySelectorAll(".button");
    const buttonsObj = {
      Backquote: buttons[0],
      Digit1: buttons[1],
      Digit2: buttons[2],
      Digit3: buttons[3],
      Digit4: buttons[4],
      Digit5: buttons[5],
      Digit6: buttons[6],
      Digit7: buttons[7],
      Digit8: buttons[8],
      Digit9: buttons[9],
      Digit0: buttons[10],
      Minus: buttons[11],
      Equal: buttons[12],
      Backspace: buttons[13],
      Tab: buttons[14],
      KeyQ: buttons[15],
      KeyW: buttons[16],
      KeyE: buttons[17],
      KeyR: buttons[18],
      KeyT: buttons[19],
      KeyY: buttons[20],
      KeyU: buttons[21],
      KeyI: buttons[22],
      KeyO: buttons[23],
      KeyP: buttons[24],
      BracketLeft: buttons[25],
      BracketRight: buttons[26],
      Backslash: buttons[27],
      Delete: buttons[28],
      CapsLock: buttons[29],
      KeyA: buttons[30],
      KeyS: buttons[31],
      KeyD: buttons[32],
      KeyF: buttons[33],
      KeyG: buttons[34],
      KeyH: buttons[35],
      KeyJ: buttons[36],
      KeyK: buttons[37],
      KeyL: buttons[38],
      Semicolon: buttons[39],
      Quote: buttons[40],
      Enter: buttons[41],
      ShiftLeft: buttons[42],
      KeyZ: buttons[43],
      KeyX: buttons[44],
      KeyC: buttons[45],
      KeyV: buttons[46],
      KeyB: buttons[47],
      KeyN: buttons[48],
      KeyM: buttons[49],
      Comma: buttons[50],
      Period: buttons[51],
      Slash: buttons[52],
      ArrowUp: buttons[53],
      ShiftRight: buttons[54],
      ControlLeft: buttons[55],
      MetaLeft: buttons[56],
      AltLeft: buttons[57],
      Space: buttons[58],
      AltRight: buttons[59],
      ArrowLeft: buttons[60],
      ArrowDown: buttons[61],
      ArrowRight: buttons[62],
      ControlRight: buttons[63],
    };
    document.querySelector(".textArea").onkeydown = function (event) {
      const nn = event.code;
      const m = buttonsObj[`${nn}`];

      m.classList.add("activeButton");
    };
    document.querySelector(".textArea").onkeyup = function (event) {
      const nn = event.code;
      const m = buttonsObj[`${nn}`];

      m.classList.remove("activeButton");
    };
  }
}

export { Highlight };
